#!/usr/bin/env bash
set -euo pipefail

# Seed 5 French banking/insurance IT companies into local D1
# Companies: BNP Paribas, Societe Generale, Credit Agricole, AXA, Natixis

CMD="npx wrangler d1 execute hackapp-db --local --command"
TS=1776520000
SRC_ID="00238d74-63da-4b37-88cb-ff4357db7e13"

# ── Company UUIDs ──
BNP_ID="a1b2c3d4-1111-4aaa-b111-000000000001"
SG_ID="a1b2c3d4-2222-4bbb-b222-000000000002"
CA_ID="a1b2c3d4-3333-4ccc-b333-000000000003"
AXA_ID="a1b2c3d4-4444-4ddd-b444-000000000004"
NAT_ID="a1b2c3d4-5555-4eee-b555-000000000005"

echo "=== Inserting 5 companies ==="

$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES
('${BNP_ID}', 'BNP Paribas', 'group.bnpparibas', 'Leading European banking group providing financial services worldwide. Major IT transformation programs including cloud migration, AI-driven trading, and DORA compliance.', 'Banking/Insurance IT', 'Universal Banking', 'Paris', 'France', 189000, 46200000000, 2024, '{\"languages\":[\"Java\",\"Python\",\"Kotlin\",\"Scala\"],\"cloud\":[\"AWS\",\"Azure\",\"GCP\"],\"data\":[\"Kafka\",\"Spark\",\"Hadoop\",\"Snowflake\"],\"devops\":[\"Kubernetes\",\"Terraform\",\"Jenkins\",\"GitLab CI\"],\"security\":[\"CyberArk\",\"Splunk\",\"Palo Alto\"],\"core_banking\":[\"Murex\",\"Calypso\",\"SAP\"]}', 1, 'https://www.linkedin.com/company/bnpparibas/', '662042449', NULL, 'active', 'enriched', ${TS}, ${TS}, ${TS}, 65, 'warm', ${TS});"

$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES
('${SG_ID}', 'Société Générale', 'societegenerale.com', 'Major French multinational banking and financial services group. Heavily investing in digital banking transformation, cybersecurity reinforcement, and AI-powered risk management.', 'Banking/Insurance IT', 'Universal Banking', 'Paris La Défense', 'France', 117000, 26800000000, 2024, '{\"languages\":[\"Java\",\"Python\",\"C++\",\"Angular\"],\"cloud\":[\"Azure\",\"AWS\",\"OpenShift\"],\"data\":[\"Kafka\",\"Elasticsearch\",\"MongoDB\",\"Databricks\"],\"devops\":[\"Kubernetes\",\"Docker\",\"Ansible\",\"ArgoCD\"],\"security\":[\"Fortinet\",\"CrowdStrike\",\"HashiCorp Vault\"],\"core_banking\":[\"Murex\",\"Finastra\",\"Temenos\"]}', 1, 'https://www.linkedin.com/company/societe-generale/', '552120222', NULL, 'active', 'enriched', ${TS}, ${TS}, ${TS}, 62, 'warm', ${TS});"

$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES
('${CA_ID}', 'Crédit Agricole', 'credit-agricole.com', 'Largest retail banking group in France and one of the largest worldwide. Driving major IT modernization across its cooperative network, cloud-first strategy, and open banking APIs.', 'Banking/Insurance IT', 'Cooperative Banking', 'Montrouge', 'France', 148000, 38000000000, 2024, '{\"languages\":[\"Java\",\"Python\",\"TypeScript\",\"Go\"],\"cloud\":[\"AWS\",\"Azure\",\"Private Cloud\"],\"data\":[\"Hadoop\",\"Spark\",\"Teradata\",\"Talend\"],\"devops\":[\"Kubernetes\",\"Jenkins\",\"Terraform\",\"SonarQube\"],\"security\":[\"Thales\",\"Gemalto\",\"IBM QRadar\"],\"core_banking\":[\"SAP\",\"Sopra Banking\",\"Temenos\"]}', 1, 'https://www.linkedin.com/company/credit-agricole/', '784608416', NULL, 'active', 'enriched', ${TS}, ${TS}, ${TS}, 58, 'qualified', ${TS});"

$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES
('${AXA_ID}', 'AXA', 'axa.com', 'Global leader in insurance and asset management. Massive investments in AI for underwriting, claims automation, cybersecurity insurance products, and cloud-native platform transformation.', 'Banking/Insurance IT', 'Insurance & Asset Management', 'Paris', 'France', 145000, 102700000000, 2024, '{\"languages\":[\"Java\",\"Python\",\"React\",\"Node.js\"],\"cloud\":[\"AWS\",\"GCP\",\"Azure\"],\"data\":[\"Snowflake\",\"Databricks\",\"Kafka\",\"Airflow\"],\"devops\":[\"Kubernetes\",\"GitHub Actions\",\"Terraform\",\"Datadog\"],\"security\":[\"Zscaler\",\"CrowdStrike\",\"Okta\"],\"insurance_platforms\":[\"Guidewire\",\"Duck Creek\",\"Sapiens\"]}', 1, 'https://www.linkedin.com/company/axa/', '572093920', NULL, 'active', 'enriched', ${TS}, ${TS}, ${TS}, 68, 'warm', ${TS});"

$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES
('${NAT_ID}', 'Natixis', 'natixis.com', 'Corporate and investment banking, asset and wealth management arm of Groupe BPCE. Strong focus on fintech partnerships, sustainable finance IT, and quantitative trading infrastructure.', 'Banking/Insurance IT', 'Corporate & Investment Banking', 'Paris', 'France', 16000, 10200000000, 2024, '{\"languages\":[\"Python\",\"Java\",\"C++\",\"Scala\"],\"cloud\":[\"Azure\",\"AWS\"],\"data\":[\"Spark\",\"Kafka\",\"kdb+\",\"InfluxDB\"],\"devops\":[\"OpenShift\",\"GitLab CI\",\"Ansible\",\"Prometheus\"],\"security\":[\"Splunk\",\"Imperva\",\"Varonis\"],\"core_banking\":[\"Murex\",\"Calypso\",\"Bloomberg Terminal\"]}', 1, 'https://www.linkedin.com/company/natixis/', '542044524', NULL, 'active', 'enriched', ${TS}, ${TS}, ${TS}, 55, 'qualified', ${TS});"

echo "=== Companies inserted ==="

# ── NEWS ITEMS ──
# BNP Paribas: 4 news
echo "=== Inserting news items ==="

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES
('b1a10001-aaaa-4000-8001-000000000001', '${BNP_ID}', '${SRC_ID}', 'BNP Paribas Achieves DORA Compliance Milestone Ahead of Deadline', 'BNP Paribas IT division completes comprehensive ICT risk management framework implementation as required by EU DORA regulation, including third-party risk assessment for 2,400+ technology vendors.', 'regulatory', 'https://group.bnpparibas/en/news/dora-compliance-2025', NULL, 'positive', 8, ${TS}, ${TS}, ${TS}),
('b1a10001-aaaa-4000-8001-000000000002', '${BNP_ID}', '${SRC_ID}', 'BNP Paribas Accelerates Multi-Cloud Migration to AWS and Azure', 'The bank announces migration of 60% of on-premise workloads to hybrid cloud by 2027, investing EUR 1.2B in cloud infrastructure and hiring 500+ cloud engineers across Europe.', 'technology', 'https://group.bnpparibas/en/news/cloud-migration-2025', NULL, 'positive', 7, ${TS}, ${TS}, ${TS}),
('b1a10001-aaaa-4000-8001-000000000003', '${BNP_ID}', '${SRC_ID}', 'BNP Paribas Deploys AI-Powered Trading Platform for Fixed Income', 'The CIB division launches proprietary AI/ML trading algorithms for fixed income markets, reducing execution latency by 40% and improving spread capture using transformer-based models.', 'technology', 'https://group.bnpparibas/en/news/ai-trading-2025', NULL, 'positive', 7, ${TS}, ${TS}, ${TS}),
('b1a10001-aaaa-4000-8001-000000000004', '${BNP_ID}', '${SRC_ID}', 'BNP Paribas Partners with Quantexa for Advanced Financial Crime Detection', 'Strategic fintech partnership to enhance KYC and AML capabilities using graph analytics and entity resolution, processing 15M+ transactions daily across 65 countries.', 'partnership', 'https://group.bnpparibas/en/news/quantexa-partnership-2025', NULL, 'positive', 6, ${TS}, ${TS}, ${TS});"

# Societe Generale: 4 news
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES
('b1a10002-bbbb-4000-8002-000000000001', '${SG_ID}', '${SRC_ID}', 'Société Générale Invests EUR 800M in Cybersecurity Overhaul', 'Multi-year cybersecurity transformation program covering zero-trust architecture deployment, SOC modernization with AI-driven threat detection, and NIS2/DORA compliance across all entities.', 'cybersecurity', 'https://societegenerale.com/en/news/cybersecurity-program-2025', NULL, 'positive', 8, ${TS}, ${TS}, ${TS}),
('b1a10002-bbbb-4000-8002-000000000002', '${SG_ID}', '${SRC_ID}', 'Société Générale Launches SG Forge Digital Asset Platform', 'Expansion of the digital asset and tokenization subsidiary SG Forge with new fintech partnerships for blockchain-based securities settlement and EUR-denominated stablecoin services.', 'partnership', 'https://societegenerale.com/en/news/sg-forge-digital-assets-2025', NULL, 'positive', 6, ${TS}, ${TS}, ${TS}),
('b1a10002-bbbb-4000-8002-000000000003', '${SG_ID}', '${SRC_ID}', 'Société Générale Migrates Core Trading Systems to OpenShift Cloud Platform', 'Migration of equity and derivatives trading infrastructure to Red Hat OpenShift, enabling containerized deployment of pricing engines and real-time risk calculators across hybrid cloud.', 'technology', 'https://societegenerale.com/en/news/cloud-trading-migration-2025', NULL, 'positive', 7, ${TS}, ${TS}, ${TS}),
('b1a10002-bbbb-4000-8002-000000000004', '${SG_ID}', '${SRC_ID}', 'Société Générale Achieves Full DORA ICT Risk Framework Certification', 'Completion of DORA-mandated ICT risk management framework covering incident reporting, digital operational resilience testing, and third-party ICT service provider oversight.', 'regulatory', 'https://societegenerale.com/en/news/dora-framework-2025', NULL, 'positive', 7, ${TS}, ${TS}, ${TS});"

# Credit Agricole: 4 news
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES
('b1a10003-cccc-4000-8003-000000000001', '${CA_ID}', '${SRC_ID}', 'Crédit Agricole Launches EUR 1.5B Digital Transformation Plan 2026-2030', 'Groupe Crédit Agricole unveils five-year IT modernization strategy spanning API-first open banking, cloud migration of regional bank systems, and AI-assisted credit scoring across 39 regional banks.', 'technology', 'https://credit-agricole.com/en/news/digital-plan-2026', NULL, 'positive', 7, ${TS}, ${TS}, ${TS}),
('b1a10003-cccc-4000-8003-000000000002', '${CA_ID}', '${SRC_ID}', 'Crédit Agricole Technologies Strengthens DORA Compliance Across Cooperative Network', 'CA Technologies coordinates DORA implementation across 39 regional banks and subsidiaries, deploying unified ICT risk monitoring platform and standardized incident reporting procedures.', 'regulatory', 'https://credit-agricole.com/en/news/dora-cooperative-compliance-2025', NULL, 'positive', 6, ${TS}, ${TS}, ${TS}),
('b1a10003-cccc-4000-8003-000000000003', '${CA_ID}', '${SRC_ID}', 'Crédit Agricole Partners with Worldline for Next-Gen Payment Infrastructure', 'Strategic fintech partnership to modernize payment processing infrastructure, supporting instant payments, embedded finance APIs, and digital wallet integration for 52 million retail clients.', 'partnership', 'https://credit-agricole.com/en/news/worldline-partnership-2025', NULL, 'positive', 6, ${TS}, ${TS}, ${TS}),
('b1a10003-cccc-4000-8003-000000000004', '${CA_ID}', '${SRC_ID}', 'Crédit Agricole Deploys AI-Powered Fraud Detection Across Retail Network', 'Real-time AI fraud detection system deployed across all regional banks, analyzing 200M+ transactions monthly using ensemble ML models, reducing false positives by 35%.', 'technology', 'https://credit-agricole.com/en/news/ai-fraud-detection-2025', NULL, 'positive', 5, ${TS}, ${TS}, ${TS});"

# AXA: 5 news
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES
('b1a10004-dddd-4000-8004-000000000001', '${AXA_ID}', '${SRC_ID}', 'AXA Completes DORA Implementation for Insurance Operations', 'AXA Group finalizes DORA compliance across insurance and asset management entities, implementing advanced ICT third-party risk management and operational resilience testing framework.', 'regulatory', 'https://axa.com/en/news/dora-insurance-compliance-2025', NULL, 'positive', 7, ${TS}, ${TS}, ${TS}),
('b1a10004-dddd-4000-8004-000000000002', '${AXA_ID}', '${SRC_ID}', 'AXA Invests EUR 2B in Cloud-Native Insurance Platform Transformation', 'Comprehensive migration from legacy insurance platforms to cloud-native microservices architecture on AWS and GCP, targeting 80% cloud workload by 2028 with Guidewire Cloud and custom APIs.', 'technology', 'https://axa.com/en/news/cloud-native-platform-2025', NULL, 'positive', 8, ${TS}, ${TS}, ${TS}),
('b1a10004-dddd-4000-8004-000000000003', '${AXA_ID}', '${SRC_ID}', 'AXA Launches AI Underwriting Engine for Commercial Lines', 'Proprietary AI underwriting platform using NLP and computer vision to automate commercial insurance risk assessment, reducing policy issuance time from 5 days to 4 hours.', 'technology', 'https://axa.com/en/news/ai-underwriting-2025', NULL, 'positive', 7, ${TS}, ${TS}, ${TS}),
('b1a10004-dddd-4000-8004-000000000004', '${AXA_ID}', '${SRC_ID}', 'AXA Strengthens Cyber Insurance with Advanced Threat Intelligence Partnership', 'Partnership with CrowdStrike and SecurityScorecard to enhance cyber insurance underwriting with real-time threat intelligence, covering EUR 5B+ in cyber risk premiums globally.', 'cybersecurity', 'https://axa.com/en/news/cyber-insurance-partnership-2025', NULL, 'positive', 6, ${TS}, ${TS}, ${TS}),
('b1a10004-dddd-4000-8004-000000000005', '${AXA_ID}', '${SRC_ID}', 'AXA Partners with Shift Technology for Claims Automation', 'Strategic fintech partnership deploying AI-driven claims fraud detection and automated claims processing, handling 10M+ claims annually with 90% straight-through processing target.', 'partnership', 'https://axa.com/en/news/shift-technology-partnership-2025', NULL, 'positive', 6, ${TS}, ${TS}, ${TS});"

# Natixis: 4 news
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES
('b1a10005-eeee-4000-8005-000000000001', '${NAT_ID}', '${SRC_ID}', 'Natixis Implements DORA-Compliant ICT Resilience Testing Program', 'Natixis CIB deploys advanced penetration testing and threat-led red team exercises as mandated by DORA, covering critical trading systems, payment infrastructure, and custody platforms.', 'regulatory', 'https://natixis.com/en/news/dora-resilience-testing-2025', NULL, 'positive', 7, ${TS}, ${TS}, ${TS}),
('b1a10005-eeee-4000-8005-000000000002', '${NAT_ID}', '${SRC_ID}', 'Natixis Migrates Quantitative Trading Infrastructure to Azure Cloud', 'Migration of quant research and algo trading workloads to Azure HPC, leveraging GPU clusters for Monte Carlo simulations and real-time derivatives pricing with 10x throughput improvement.', 'technology', 'https://natixis.com/en/news/azure-quant-migration-2025', NULL, 'positive', 7, ${TS}, ${TS}, ${TS}),
('b1a10005-eeee-4000-8005-000000000003', '${NAT_ID}', '${SRC_ID}', 'Natixis Partners with Opensee for Real-Time Risk Analytics', 'Fintech partnership to deploy in-memory risk analytics platform for real-time P&L, VaR, and stress testing calculations across CIB trading desks, replacing legacy batch-based systems.', 'partnership', 'https://natixis.com/en/news/opensee-risk-analytics-2025', NULL, 'positive', 6, ${TS}, ${TS}, ${TS}),
('b1a10005-eeee-4000-8005-000000000004', '${NAT_ID}', '${SRC_ID}', 'Natixis Enhances Cybersecurity with AI-Driven SOC Transformation', 'Complete SOC modernization program deploying SOAR, XDR, and AI-powered threat hunting capabilities to protect trading and asset management platforms processing EUR 400B+ in daily transactions.', 'cybersecurity', 'https://natixis.com/en/news/soc-transformation-2025', NULL, 'positive', 6, ${TS}, ${TS}, ${TS});"

echo "=== News inserted ==="

# ── PROSPECT SCORES ──
# 50 criteria scored realistically for banking/insurance IT
# Scores: 0-10 per criterion
echo "=== Inserting prospect scores ==="

# BNP Paribas - total 65
$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES
('c1d2e3f4-1111-4111-a111-000000000001', '${BNP_ID}', 9, 7, 10, 8, 10, 9, 10, 8, 6, 7, 5, 7, 3, 2, 4, 3, 8, 8, 5, 4, 7, 8, 9, 5, 6, 7, 4, 7, 8, 6, 9, 4, 8, 7, 5, 6, 9, 7, 5, 3, 9, 4, 9, 1, 8, 6, 2, 7, 65, 'warm', ${TS}, ${TS}, ${TS});"

# Societe Generale - total 62
$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES
('c1d2e3f4-2222-4222-a222-000000000002', '${SG_ID}', 9, 7, 9, 7, 10, 9, 10, 7, 5, 6, 4, 7, 2, 2, 6, 5, 8, 7, 6, 5, 7, 7, 8, 6, 5, 6, 3, 6, 8, 5, 8, 3, 7, 6, 6, 4, 9, 8, 6, 4, 9, 3, 9, 1, 7, 5, 3, 6, 62, 'warm', ${TS}, ${TS}, ${TS});"

# Credit Agricole - total 58
$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES
('c1d2e3f4-3333-4333-a333-000000000003', '${CA_ID}', 9, 7, 10, 6, 8, 7, 10, 6, 5, 5, 4, 6, 2, 3, 5, 3, 7, 6, 4, 4, 6, 6, 7, 4, 4, 5, 5, 6, 7, 5, 8, 5, 7, 6, 4, 3, 8, 8, 6, 3, 8, 3, 8, 1, 7, 5, 2, 6, 58, 'qualified', ${TS}, ${TS}, ${TS});"

# AXA - total 68
$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES
('c1d2e3f4-4444-4444-a444-000000000004', '${AXA_ID}', 8, 6, 10, 8, 10, 9, 10, 8, 7, 8, 6, 8, 3, 2, 4, 2, 9, 9, 5, 4, 8, 7, 9, 5, 7, 7, 5, 8, 9, 7, 9, 3, 9, 8, 5, 5, 9, 6, 4, 3, 10, 5, 9, 1, 8, 7, 2, 8, 68, 'warm', ${TS}, ${TS}, ${TS});"

# Natixis - total 55
$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES
('c1d2e3f4-5555-4555-a555-000000000005', '${NAT_ID}', 9, 7, 7, 6, 10, 9, 9, 7, 5, 6, 4, 6, 2, 1, 5, 4, 7, 6, 5, 4, 7, 8, 8, 5, 4, 6, 2, 5, 7, 5, 7, 3, 7, 5, 4, 3, 8, 7, 5, 4, 8, 3, 8, 1, 7, 4, 3, 5, 55, 'qualified', ${TS}, ${TS}, ${TS});"

echo "=== Prospect scores inserted ==="
echo "=== SEED COMPLETE ==="
