#!/bin/bash
# Seed 10 French Construction & Infrastructure companies into local D1
# Companies: Vinci Construction, Bouygues Construction, Eiffage, Colas, Egis, Setec, Artelia, Tractebel France, Systra, SGP
set -e

DB="hackapp-db"
CMD="npx wrangler d1 execute $DB --local --command"
SRC="00238d74-63da-4b37-88cb-ff4357db7e13"
TS=1776520000

echo "=== Seeding 10 French Construction companies ==="

# ─────────────────────────────────────────────
# 1. VINCI CONSTRUCTION
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00001"
echo ">> Vinci Construction"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Vinci Construction', 'vinci-construction.com', 'World leading construction company and subsidiary of Vinci SA. Operates across building, civil engineering, hydraulic infrastructure, and major projects including Grand Paris Express metro lines.', 'Construction', 'Civil Engineering & Major Projects', 'Nanterre', 'France', 68000, 28500000000, 2025, '{\"languages\":[\"Python\",\"C#\"],\"frameworks\":[\"Autodesk BIM 360\",\"Revit\",\"Tekla\"],\"platforms\":[\"Azure\",\"On-Premise\"],\"cloud\":[\"Azure\"],\"tools\":[\"BIM\",\"Digital Twin\",\"Primavera P6\",\"Dassault 3DEXPERIENCE\"]}', 1, 'https://www.linkedin.com/company/vinci-construction/', '381390660', NULL, 'active', 'enriched', $TS, $TS, $TS, 68, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0001-4000-a001-000000000001', '$CID', '$SRC', 'Vinci Construction delivers TBM breakthrough on Grand Paris Express Line 15 South', 'Vinci Construction''s tunnel boring machine completes critical section of Grand Paris Express Line 15 South between Villejuif and Issy-les-Moulineaux, marking a major milestone for the largest European infrastructure project.', 'project_milestone', 'https://www.vinci-construction.com/gpe-line15-breakthrough', NULL, 'positive', 9, 1775800000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0001-4000-a001-000000000002', '$CID', '$SRC', 'Vinci Construction deploys digital twin platform across all Grand Paris Express worksites', 'Vinci Construction rolls out a unified digital twin environment using Dassault 3DEXPERIENCE to monitor real-time progress, safety, and logistics on all its GPE construction sites.', 'digital_transformation', 'https://www.vinci-construction.com/digital-twin-gpe', NULL, 'positive', 8, 1775600000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0001-4000-a001-000000000003', '$CID', '$SRC', 'Vinci Construction launches low-carbon concrete program for infrastructure projects', 'Vinci Construction commits to reducing embodied carbon by 40% on new projects through proprietary Exegy low-carbon concrete and circular economy partnerships.', 'sustainability', 'https://www.vinci-construction.com/low-carbon-concrete', NULL, 'positive', 7, 1775400000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0001-4000-a001-000000000001', '$CID', 90, 88, 95, 70, 90, 85, 95, 80, 65, 72, 85, 60, 35, 75, 62, 50, 80, 88, 70, 65, 72, 80, 78, 55, 75, 65, 80, 60, 70, 85, 65, 55, 60, 78, 50, 65, 82, 60, 55, 50, 85, 72, 80, 20, 75, 90, 30, 78, 68, 'warm', $TS, $TS, $TS);"

# ─────────────────────────────────────────────
# 2. BOUYGUES CONSTRUCTION
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00002"
echo ">> Bouygues Construction"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Bouygues Construction', 'bouygues-construction.com', 'Major French construction group and subsidiary of Bouygues SA. Active in building, civil works, energy and services. Key player in Grand Paris Express and high-speed rail LGV projects in France.', 'Construction', 'Building & Civil Works', 'Guyancourt', 'France', 56000, 13500000000, 2025, '{\"languages\":[\"Python\",\"JavaScript\"],\"frameworks\":[\"Revit\",\"Navisworks\",\"Power BI\"],\"platforms\":[\"Microsoft Azure\",\"On-Premise\"],\"cloud\":[\"Azure\",\"Microsoft 365\"],\"tools\":[\"BIM\",\"Trimble Connect\",\"MS Project\",\"Lean Construction\"]}', 1, 'https://www.linkedin.com/company/bouygues-construction/', '572015246', NULL, 'active', 'enriched', $TS, $TS, $TS, 65, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0002-4000-a002-000000000001', '$CID', '$SRC', 'Bouygues Construction wins EUR 2.1B lot for Grand Paris Express Line 16 stations', 'Bouygues Construction secures major contract for design-build of three key stations on GPE Line 16, including complex underground interchange at Saint-Denis Pleyel.', 'contract_win', 'https://www.bouygues-construction.com/gpe-line16-contract', NULL, 'positive', 9, 1775700000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0002-4000-a002-000000000002', '$CID', '$SRC', 'Bouygues Construction advances BIM Level 3 adoption with AI-powered clash detection', 'Bouygues Construction integrates AI-based clash detection into its BIM Level 3 workflow, reducing design conflicts by 60% on active building projects.', 'digital_transformation', 'https://www.bouygues-construction.com/bim-ai-clash', NULL, 'positive', 8, 1775500000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0002-4000-a002-000000000003', '$CID', '$SRC', 'Bouygues Construction targets net-zero on all new buildings by 2030 with RE2025 compliance', 'Bouygues Construction announces comprehensive sustainable construction roadmap aligned with France RE2025 regulation, deploying bio-sourced materials and energy-positive designs.', 'sustainability', 'https://www.bouygues-construction.com/re2025-roadmap', NULL, 'positive', 7, 1775300000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0002-4000-a002-000000000004', '$CID', '$SRC', 'Bouygues Construction awarded LGV Bordeaux-Toulouse civil works package', 'Bouygues Construction leads consortium for major earthworks and viaduct construction on the LGV Sud-Ouest high-speed rail line between Bordeaux and Toulouse, valued at EUR 850M.', 'contract_win', 'https://www.bouygues-construction.com/lgv-bordeaux-toulouse', NULL, 'positive', 8, 1775100000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0002-4000-a002-000000000001', '$CID', 88, 85, 92, 68, 88, 82, 92, 78, 60, 70, 82, 58, 32, 72, 60, 48, 78, 85, 68, 62, 70, 78, 75, 52, 72, 62, 80, 58, 68, 82, 65, 52, 58, 75, 48, 62, 80, 58, 52, 48, 82, 70, 78, 18, 72, 88, 28, 75, 65, 'warm', $TS, $TS, $TS);"

# ─────────────────────────────────────────────
# 3. EIFFAGE
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00003"
echo ">> Eiffage"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Eiffage', 'eiffage.com', 'Third-largest French construction group. Operates across construction, infrastructure, energy systems and concessions. Major contractor on Grand Paris Express and Millau Viaduct operator. Strong push into sustainable and modular construction.', 'Construction', 'Infrastructure & Concessions', 'Velizy-Villacoublay', 'France', 73500, 21800000000, 2025, '{\"languages\":[\"Python\",\"C++\"],\"frameworks\":[\"Revit\",\"Tekla Structures\",\"CATIA\"],\"platforms\":[\"AWS\",\"On-Premise\"],\"cloud\":[\"AWS\"],\"tools\":[\"BIM\",\"Dassault 3DEXPERIENCE\",\"IoT Sensors\",\"Drone Surveying\"]}', 1, 'https://www.linkedin.com/company/eiffage/', '709702738', NULL, 'active', 'enriched', $TS, $TS, $TS, 66, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0003-4000-a003-000000000001', '$CID', '$SRC', 'Eiffage Genie Civil completes tunneling on Grand Paris Express Line 14 South extension', 'Eiffage''s civil engineering division completes the tunnel boring campaign on GPE Line 14 South to Orly Airport, with station fit-out now underway ahead of 2026 opening.', 'project_milestone', 'https://www.eiffage.com/gpe-line14-tunneling', NULL, 'positive', 9, 1775800000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0003-4000-a003-000000000002', '$CID', '$SRC', 'Eiffage launches Sekoya low-carbon construction platform with 200 eco-solutions', 'Eiffage expands its Sekoya sustainable construction platform to 200 verified low-carbon solutions covering materials, energy, and circular economy for infrastructure projects.', 'sustainability', 'https://www.eiffage.com/sekoya-platform', NULL, 'positive', 7, 1775500000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0003-4000-a003-000000000003', '$CID', '$SRC', 'Eiffage deploys IoT-based structural health monitoring on major bridge assets', 'Eiffage Infrastructure installs connected IoT sensor networks on 15 major bridge and viaduct assets for continuous structural health monitoring, feeding a centralized digital twin dashboard.', 'digital_transformation', 'https://www.eiffage.com/iot-bridge-monitoring', NULL, 'positive', 8, 1775300000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0003-4000-a003-000000000001', '$CID', 90, 86, 94, 72, 85, 84, 94, 76, 62, 74, 84, 62, 30, 78, 64, 52, 76, 86, 72, 68, 74, 82, 80, 58, 78, 68, 80, 62, 72, 88, 65, 58, 62, 80, 52, 60, 78, 62, 58, 52, 88, 78, 82, 15, 78, 85, 32, 80, 66, 'warm', $TS, $TS, $TS);"

# ─────────────────────────────────────────────
# 4. COLAS
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00004"
echo ">> Colas"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Colas', 'colas.com', 'World leader in road construction and maintenance, subsidiary of Bouygues SA. Specializes in transport infrastructure, urban development, and construction materials. Operates in 50+ countries with strong expertise in rail infrastructure and LGV projects.', 'Construction', 'Road & Rail Infrastructure', 'Paris', 'France', 62000, 16800000000, 2025, '{\"languages\":[\"Python\",\"Java\"],\"frameworks\":[\"GIS/ArcGIS\",\"Power BI\"],\"platforms\":[\"Azure\",\"On-Premise\"],\"cloud\":[\"Azure\"],\"tools\":[\"BIM\",\"Topcon\",\"Machine Guidance Systems\",\"Pavement Management System\"]}', 1, 'https://www.linkedin.com/company/colas/', '552025314', NULL, 'active', 'enriched', $TS, $TS, $TS, 58, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0004-4000-a004-000000000001', '$CID', '$SRC', 'Colas Rail wins major track-laying contract for LGV Bordeaux-Dax high-speed rail', 'Colas Rail secures EUR 620M contract for ballast, track-laying and catenary installation on the LGV Sud-Ouest extension between Bordeaux and Dax.', 'contract_win', 'https://www.colas.com/lgv-bordeaux-dax-contract', NULL, 'positive', 9, 1775700000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0004-4000-a004-000000000002', '$CID', '$SRC', 'Colas develops Wattway solar road technology for urban infrastructure', 'Colas continues scaling its Wattway photovoltaic road surface technology, deploying pilot installations across French urban zones for sustainable infrastructure.', 'innovation', 'https://www.colas.com/wattway-urban-solar', NULL, 'positive', 7, 1775400000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0004-4000-a004-000000000003', '$CID', '$SRC', 'Colas deploys machine guidance and 3D modeling across road construction fleet', 'Colas rolls out GPS-guided machine control and 3D terrain modeling to its heavy equipment fleet, improving grading accuracy and reducing material waste by 25%.', 'digital_transformation', 'https://www.colas.com/machine-guidance-3d', NULL, 'positive', 8, 1775200000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0004-4000-a004-000000000001', '$CID', 85, 82, 92, 65, 90, 80, 90, 74, 58, 68, 78, 55, 28, 70, 58, 45, 75, 82, 65, 60, 68, 72, 70, 50, 70, 60, 80, 55, 62, 80, 65, 50, 55, 72, 45, 58, 75, 55, 50, 48, 80, 68, 75, 15, 70, 82, 25, 72, 58, 'warm', $TS, $TS, $TS);"

# ─────────────────────────────────────────────
# 5. EGIS
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00005"
echo ">> Egis"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Egis', 'egis-group.com', 'International consulting and engineering group specializing in transport, urban development, building, water, environment and energy. Major engineering consultant on Grand Paris Express. Owned by Caisse des Depots.', 'Construction', 'Engineering Consulting & Design', 'Guyancourt', 'France', 18000, 1700000000, 2025, '{\"languages\":[\"Python\",\"MATLAB\"],\"frameworks\":[\"Revit\",\"Civil 3D\",\"OpenRoads\"],\"platforms\":[\"Azure\",\"AWS\"],\"cloud\":[\"Azure\",\"AWS\"],\"tools\":[\"BIM\",\"Digital Twin\",\"GIS\",\"Traffic Simulation\",\"Computational Fluid Dynamics\"]}', 1, 'https://www.linkedin.com/company/egis/', '702027085', NULL, 'active', 'enriched', $TS, $TS, $TS, 62, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0005-4000-a005-000000000001', '$CID', '$SRC', 'Egis leads engineering design for Grand Paris Express Line 17 and 18', 'Egis serves as lead engineering consultant for design and construction supervision of GPE Lines 17 (Le Bourget to CDG Airport) and 18 (Orly to Versailles), covering tunnels, stations and systems.', 'contract_win', 'https://www.egis-group.com/gpe-lines-17-18', NULL, 'positive', 9, 1775800000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0005-4000-a005-000000000002', '$CID', '$SRC', 'Egis develops city-scale digital twin for smart urban mobility planning', 'Egis launches an integrated digital twin platform combining traffic simulation, air quality modeling and multimodal transport optimization for metropolitan planning authorities.', 'digital_transformation', 'https://www.egis-group.com/digital-twin-mobility', NULL, 'positive', 8, 1775500000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0005-4000-a005-000000000003', '$CID', '$SRC', 'Egis acquires UK-based sustainable engineering firm to expand green infrastructure practice', 'Egis strengthens its sustainable construction and climate resilience capabilities through acquisition, adding 500 environmental engineers to its global workforce.', 'acquisition', 'https://www.egis-group.com/uk-acquisition', NULL, 'positive', 7, 1775300000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0005-4000-a005-000000000001', '$CID', 88, 85, 78, 80, 88, 82, 88, 75, 68, 78, 65, 70, 35, 72, 55, 42, 72, 85, 72, 68, 75, 85, 82, 55, 78, 65, 80, 65, 75, 82, 65, 62, 65, 80, 55, 72, 70, 65, 58, 52, 82, 72, 78, 12, 72, 80, 28, 78, 62, 'warm', $TS, $TS, $TS);"

# ─────────────────────────────────────────────
# 6. SETEC
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00006"
echo ">> Setec"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Setec', 'setec.fr', 'Independent French engineering and consulting group. Key player in infrastructure design including transport, buildings, water, and environment. Major engineering role on Grand Paris Express stations and LGV projects.', 'Construction', 'Engineering Consulting & Design', 'Paris', 'France', 3800, 520000000, 2025, '{\"languages\":[\"Python\",\"MATLAB\",\"Fortran\"],\"frameworks\":[\"Revit\",\"Robot Structural\",\"PLAXIS\"],\"platforms\":[\"On-Premise\",\"Azure\"],\"cloud\":[\"Azure\"],\"tools\":[\"BIM\",\"FEM Analysis\",\"Geotechnical Modeling\",\"Traffic Simulation\"]}', 1, 'https://www.linkedin.com/company/setec/', '572191849', NULL, 'active', 'enriched', $TS, $TS, $TS, 55, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0006-4000-a006-000000000001', '$CID', '$SRC', 'Setec delivers structural engineering for 12 Grand Paris Express stations', 'Setec provides structural and geotechnical engineering design for 12 underground stations across multiple GPE lines, managing complex geological conditions in Ile-de-France.', 'project_milestone', 'https://www.setec.fr/gpe-stations-engineering', NULL, 'positive', 9, 1775800000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0006-4000-a006-000000000002', '$CID', '$SRC', 'Setec adopts BIM-to-FEM automated workflow for structural analysis', 'Setec develops proprietary BIM-to-FEM pipeline automating the transfer of architectural models to finite element structural analysis, cutting design iteration time by 40%.', 'digital_transformation', 'https://www.setec.fr/bim-fem-automation', NULL, 'positive', 8, 1775500000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0006-4000-a006-000000000003', '$CID', '$SRC', 'Setec appointed engineering consultant for LGV Montpellier-Perpignan design studies', 'Setec leads preliminary and detailed design studies for the new LGV Mediterranean high-speed rail line between Montpellier and Perpignan, covering alignment, tunnels and viaducts.', 'contract_win', 'https://www.setec.fr/lgv-montpellier-perpignan', NULL, 'positive', 8, 1775200000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0006-4000-a006-000000000001', '$CID', 85, 82, 65, 75, 90, 78, 85, 72, 62, 75, 55, 65, 30, 68, 52, 40, 68, 80, 68, 65, 72, 82, 78, 50, 72, 60, 80, 60, 72, 78, 65, 58, 60, 75, 42, 48, 72, 60, 55, 48, 78, 65, 72, 10, 68, 75, 22, 72, 55, 'warm', $TS, $TS, $TS);"

# ─────────────────────────────────────────────
# 7. ARTELIA
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00007"
echo ">> Artelia"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Artelia', 'arteliagroup.com', 'Independent French multidisciplinary engineering and project management group. Covers buildings, water, transport infrastructure, energy and environment. Employee-owned. Active in BIM, digital twin and sustainable construction consulting.', 'Construction', 'Engineering & Project Management', 'Lyon', 'France', 8500, 950000000, 2025, '{\"languages\":[\"Python\",\"JavaScript\"],\"frameworks\":[\"Revit\",\"Dynamo\",\"Power BI\"],\"platforms\":[\"Azure\",\"AWS\"],\"cloud\":[\"Azure\",\"AWS\"],\"tools\":[\"BIM\",\"Digital Twin\",\"Computational Design\",\"Energy Simulation\"]}', 1, 'https://www.linkedin.com/company/arteliagroup/', '378tried948', NULL, 'active', 'enriched', $TS, $TS, $TS, 60, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0007-4000-a007-000000000001', '$CID', '$SRC', 'Artelia selected as BIM manager for major hospital complex in Ile-de-France', 'Artelia appointed to lead BIM management and digital coordination for a EUR 450M hospital campus project, implementing full BIM Level 2 methodology from design through construction.', 'contract_win', 'https://www.arteliagroup.com/bim-hospital-idf', NULL, 'positive', 8, 1775700000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0007-4000-a007-000000000002', '$CID', '$SRC', 'Artelia develops computational design tools for optimized low-carbon structures', 'Artelia''s R&D team creates parametric design tools using generative algorithms to optimize structural forms for minimal material usage and carbon footprint.', 'digital_transformation', 'https://www.arteliagroup.com/computational-design', NULL, 'positive', 8, 1775400000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0007-4000-a007-000000000003', '$CID', '$SRC', 'Artelia expands sustainable construction advisory with lifecycle carbon assessment offering', 'Artelia launches comprehensive lifecycle carbon assessment service aligned with RE2020 and EU taxonomy, helping clients achieve net-zero building targets.', 'sustainability', 'https://www.arteliagroup.com/lifecycle-carbon', NULL, 'positive', 7, 1775200000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0007-4000-a007-000000000001', '$CID', 86, 84, 72, 78, 82, 80, 82, 78, 65, 76, 58, 68, 32, 68, 50, 38, 70, 82, 70, 65, 74, 84, 80, 52, 75, 62, 80, 62, 74, 80, 65, 60, 62, 78, 48, 52, 68, 62, 55, 50, 80, 70, 75, 10, 70, 78, 25, 75, 60, 'warm', $TS, $TS, $TS);"

# ─────────────────────────────────────────────
# 8. TRACTEBEL FRANCE
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00008"
echo ">> Tractebel France"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Tractebel France', 'tractebel-engie.com', 'French subsidiary of Tractebel (ENGIE group). Global engineering and consulting company specializing in energy, nuclear, water and infrastructure. Key role in French nuclear new-build, LGV studies and sustainable infrastructure design.', 'Construction', 'Energy & Infrastructure Engineering', 'Gennevilliers', 'France', 5200, 780000000, 2025, '{\"languages\":[\"Python\",\"MATLAB\",\"Fortran\"],\"frameworks\":[\"ANSYS\",\"CATIA\",\"Civil 3D\"],\"platforms\":[\"Azure\",\"On-Premise\"],\"cloud\":[\"Azure\"],\"tools\":[\"BIM\",\"CFD\",\"Nuclear Safety Analysis\",\"Hydraulic Modeling\"]}', 1, 'https://www.linkedin.com/company/tractebel/', '389718625', NULL, 'active', 'enriched', $TS, $TS, $TS, 56, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0008-4000-a008-000000000001', '$CID', '$SRC', 'Tractebel provides engineering oversight for LGV Rhin-Rhone Phase 2 preliminary studies', 'Tractebel leads multidisciplinary preliminary design studies for the LGV Rhin-Rhone Eastern branch Phase 2, covering geotechnical, hydraulic, and environmental assessments.', 'contract_win', 'https://www.tractebel-engie.com/lgv-rhin-rhone', NULL, 'positive', 8, 1775700000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0008-4000-a008-000000000002', '$CID', '$SRC', 'Tractebel deploys digital twin for dam and hydropower asset management', 'Tractebel develops integrated digital twin solutions for monitoring and optimizing the performance of dam infrastructure and hydropower plants across France.', 'digital_transformation', 'https://www.tractebel-engie.com/digital-twin-hydro', NULL, 'positive', 8, 1775400000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0008-4000-a008-000000000003', '$CID', '$SRC', 'Tractebel wins sustainable infrastructure design contract for ENGIE green hydrogen hub', 'Tractebel designs the civil and process engineering for a major green hydrogen production facility in Northern France, integrating renewable energy and electrolysis infrastructure.', 'sustainability', 'https://www.tractebel-engie.com/green-hydrogen-hub', NULL, 'positive', 7, 1775200000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0008-4000-a008-000000000001', '$CID', 82, 80, 70, 78, 82, 78, 85, 72, 60, 75, 58, 65, 30, 70, 52, 40, 68, 78, 65, 62, 70, 80, 78, 48, 72, 58, 80, 62, 70, 78, 65, 58, 60, 75, 48, 58, 72, 58, 52, 50, 80, 72, 78, 12, 72, 78, 25, 72, 56, 'warm', $TS, $TS, $TS);"

# ─────────────────────────────────────────────
# 9. SYSTRA
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00009"
echo ">> Systra"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Systra', 'systra.com', 'World-leading transport engineering and consulting group, jointly owned by SNCF and RATP. Specializes in rail, metro, tramway and mobility infrastructure. Key engineering partner on Grand Paris Express and French LGV network.', 'Construction', 'Transport Engineering & Consulting', 'Paris', 'France', 10300, 1200000000, 2025, '{\"languages\":[\"Python\",\"C++\",\"MATLAB\"],\"frameworks\":[\"Revit\",\"Civil 3D\",\"MicroStation\"],\"platforms\":[\"Azure\",\"On-Premise\"],\"cloud\":[\"Azure\"],\"tools\":[\"BIM\",\"Rail Design\",\"Traffic Simulation\",\"RAMS Analysis\",\"Signaling Systems Design\"]}', 1, 'https://www.linkedin.com/company/systra/', '387791631', NULL, 'active', 'enriched', $TS, $TS, $TS, 64, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0009-4000-a009-000000000001', '$CID', '$SRC', 'Systra leads systems engineering for Grand Paris Express automated metro', 'Systra provides systems integration and signaling engineering for the fully automated driverless operation of Grand Paris Express lines, ensuring interoperability across all 200km of new metro.', 'project_milestone', 'https://www.systra.com/gpe-systems-engineering', NULL, 'positive', 9, 1775800000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0009-4000-a009-000000000002', '$CID', '$SRC', 'Systra builds BIM-driven digital twin for entire LGV network lifecycle management', 'Systra develops a comprehensive digital twin integrating BIM models with real-time operational data for lifecycle management of France''s high-speed rail network.', 'digital_transformation', 'https://www.systra.com/lgv-digital-twin', NULL, 'positive', 9, 1775500000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0009-4000-a009-000000000003', '$CID', '$SRC', 'Systra wins consultancy contract for Lyon-Turin rail tunnel cross-border coordination', 'Systra appointed as lead consultant for cross-border engineering coordination on the Lyon-Turin base tunnel, the longest rail tunnel under construction in Europe.', 'contract_win', 'https://www.systra.com/lyon-turin-consultancy', NULL, 'positive', 8, 1775200000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0009-4000-a009-000000000004', '$CID', '$SRC', 'Systra develops AI-powered predictive maintenance for rail infrastructure', 'Systra integrates machine learning models with track sensor data to predict rail infrastructure degradation, reducing unplanned maintenance by 35% on pilot LGV sections.', 'digital_transformation', 'https://www.systra.com/ai-predictive-maintenance', NULL, 'positive', 8, 1775000000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0009-4000-a009-000000000001', '$CID', 90, 88, 75, 82, 90, 85, 88, 78, 65, 80, 62, 68, 28, 75, 55, 45, 72, 88, 75, 70, 78, 88, 85, 55, 80, 65, 80, 68, 78, 85, 65, 60, 65, 82, 50, 55, 75, 62, 55, 52, 85, 78, 80, 10, 75, 85, 28, 80, 64, 'warm', $TS, $TS, $TS);"

# ─────────────────────────────────────────────
# 10. SGP (SOCIETE DU GRAND PARIS)
# ─────────────────────────────────────────────
CID="d1c01a01-aaaa-4b01-b001-c0c0c0c00010"
echo ">> SGP (Societe du Grand Paris)"
$CMD "INSERT INTO companies (id, name, domain, description, sector, subsector, location_city, location_country, employee_count, revenue_eur, revenue_year, tech_stack, uses_consulting_services, linkedin_url, siren, logo_url, status, enrichment_status, last_enriched_at, created_at, updated_at, prospect_score, prospect_band, scored_at) VALUES ('$CID', 'Societe du Grand Paris', 'societedugrandparis.fr', 'French public establishment responsible for designing and building the Grand Paris Express, the largest transport infrastructure project in Europe. Manages 200km of new automated metro lines, 68 stations, and EUR 36B+ budget.', 'Construction', 'Public Infrastructure Authority', 'Saint-Denis', 'France', 1200, 5500000000, 2025, '{\"languages\":[\"Python\",\"JavaScript\"],\"frameworks\":[\"Power BI\",\"Revit\"],\"platforms\":[\"Azure\",\"On-Premise\"],\"cloud\":[\"Azure\"],\"tools\":[\"BIM\",\"Digital Twin\",\"GIS\",\"Project Portfolio Management\",\"Primavera P6\"]}', 1, 'https://www.linkedin.com/company/societe-du-grand-paris/', '525762282', NULL, 'active', 'enriched', $TS, $TS, $TS, 70, 'warm', $TS);"

$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0010-4000-a010-000000000001', '$CID', '$SRC', 'SGP accelerates Grand Paris Express delivery with revised 2026-2032 commissioning calendar', 'Societe du Grand Paris publishes updated delivery schedule: Line 14 South opening in 2026 for Olympics legacy, Lines 15/16/17 phased through 2032, with total project budget at EUR 36.1B.', 'project_milestone', 'https://www.societedugrandparis.fr/delivery-calendar-2026', NULL, 'positive', 10, 1775900000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0010-4000-a010-000000000002', '$CID', '$SRC', 'SGP mandates BIM Level 2 across all Grand Paris Express contracts', 'Societe du Grand Paris enforces mandatory BIM Level 2 requirements for all construction and engineering contractors, with a roadmap toward full digital twin integration by 2028.', 'digital_transformation', 'https://www.societedugrandparis.fr/bim-mandate', NULL, 'positive', 9, 1775600000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0010-4000-a010-000000000003', '$CID', '$SRC', 'SGP publishes Grand Paris Express environmental performance report with circular economy targets', 'SGP reports 3.2M tonnes of excavated earth reused, 85% waste recycling rate, and sets new circular economy targets for remaining construction phases of the Grand Paris Express network.', 'sustainability', 'https://www.societedugrandparis.fr/environmental-report', NULL, 'positive', 8, 1775300000, 1776000000, $TS);"
$CMD "INSERT INTO news (id, company_id, source_id, title, summary, category, source_url, report_key, sentiment, relevance_score, published_at, extracted_at, created_at) VALUES ('nc010001-0010-4000-a010-000000000004', '$CID', '$SRC', 'SGP deploys unified project data platform connecting 160+ construction sites', 'Societe du Grand Paris launches centralized cloud-based data platform aggregating real-time progress, safety and cost data from all 160+ active GPE construction sites.', 'digital_transformation', 'https://www.societedugrandparis.fr/data-platform', NULL, 'positive', 9, 1775100000, 1776000000, $TS);"

$CMD "INSERT INTO prospect_scores (id, company_id, sector_alignment, naf_code_match, company_size, rd_department_size, geographic_proximity, regional_specialization, company_maturity, organizational_structure, revenue_growth_gap, rd_spending_trend, capex_spikes, capex_to_opex_shift, recent_funding, public_grants, margin_compression, hiring_freeze_with_projects, external_spend_in_financials, engineering_job_volume, stale_job_postings, repeated_repostings, contract_freelance_language, rare_skills_demand, emerging_tech_demand, high_turnover_signals, recruiter_hiring_wave, above_market_salaries, physical_expansion, new_product_launch, platform_migration, program_milestones, digital_transformation, erp_plm_migration, cloud_migration, strategic_partnerships, leadership_change, ma_activity, existing_consulting_usage, legacy_modernization, tech_debt_indicators, cybersecurity_gaps, industry_specific_software, iot_industry4_adoption, eu_regulatory_pressure, french_defense_budget, certification_needs, major_contract_won, crisis_event, industry_event_presence, total_score, score_label, scored_at, created_at, updated_at) VALUES ('ps010001-0010-4000-a010-000000000001', '$CID', 92, 90, 60, 65, 92, 90, 78, 70, 72, 68, 90, 75, 90, 95, 60, 55, 88, 78, 60, 58, 65, 75, 72, 48, 70, 55, 80, 70, 78, 92, 65, 62, 68, 85, 55, 40, 90, 65, 52, 55, 78, 65, 88, 10, 80, 92, 35, 85, 70, 'warm', $TS, $TS, $TS);"

echo ""
echo "=== Seeding complete! ==="
echo "Verifying counts..."
$CMD "SELECT 'companies' as tbl, COUNT(*) as cnt FROM companies WHERE sector='Construction' UNION ALL SELECT 'news', COUNT(*) FROM news WHERE company_id LIKE 'd1c01a01-aaaa-4b01-b001-c0c0c0c000%' UNION ALL SELECT 'prospect_scores', COUNT(*) FROM prospect_scores WHERE company_id LIKE 'd1c01a01-aaaa-4b01-b001-c0c0c0c000%';"
